### ISSUE TITLE
The receiver should validate the message origin against a whitelist, so we don't have security leaks

### ISSUE THREAD

**Issue by adrian0cg** [20Minuten/autofit#1]

**Comment by veganben** [comment]
I'm not sure how this would be implemented.
The white list would then need to reside in the receiving side somewhere. This would mean that anyone using the autofit functionality would have to specifically register with us, and we would have to maintain that list. 
The point is that any unknown client wishing to provide content to be included in an iframe can do so as long as they have been approved to provide content (ie: advertisers, internal clients, ourselves). Developer involvement should be zero.

The input into the receiving function is twice sanitized, the only DOM element which can be affected is the iFrame (which has to identify itself in its message)which sent the message, and the only thing that can be changed is the height (hardcoded, not parameterised) via the DOM-native "setAttribute" method. 

The whole thing is a self-invoking function with no global leaks. 
The only increased security I could think of would be to put a parameter check in to ensure that the incoming "e" was indeed a browser event. But it's probably overkill.
